receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    tls:
      insecure: true
  prometheus:
    endpoint: otel-collector:8889
    namespace: default

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging , zipkin ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging , prometheus ]
